### ISSUE TITLE
Abort of nxagent-3.5.99.13 on CentOS 7

### ISSUE THREAD

**Issue by realsimix** [ArcticaProject/nx-libs#652]
I've tried a build of current nxagent-3.5.99.13 and it fails to start nxagent on CentOS 7 / x86_64.

```
[simix@alpha bin]$ ldd ./nxagent
	linux-vdso.so.1 =>  (0x00007ffd70007000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f6e27337000)
	libXcomp.so.3 => /home/simix/bin/libXcomp.so.3 (0x00007f6e2700f000)
	libXcompshad.so.3 => /home/simix/bin/libXcompshad.so.3 (0x00007f6e26dff000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f6e26bef000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f6e269e7000)
	libXfont.so.1 => /lib64/libXfont.so.1 (0x00007f6e267af000)
	libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00007f6e265a7000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007f6e2639f000)
	libXdmcp.so.6 => /lib64/libXdmcp.so.6 (0x00007f6e26197000)
	libNX_X11.so.6 => /home/simix/bin/libNX_X11.so.6 (0x00007f6e25e57000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f6e25c3f000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f6e25a27000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6e2571f000)
	libXpm.so.4 => /lib64/libXpm.so.4 (0x00007f6e25507000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f6e25197000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007f6e24ee7000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f6e24cb7000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f6e24a5f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6e24697000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f6e2446f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f6e24267000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f6e23f5f000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f6e23d47000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f6e23b3f000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00007f6e2392f000)
	libXtst.so.6 => /lib64/libXtst.so.6 (0x00007f6e23727000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f6e2347f000)
	libfontenc.so.1 => /lib64/libfontenc.so.1 (0x00007f6e23277000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6e23057000)
	/lib64/ld-linux-x86-64.so.2 (0x000056194a8ab000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f6e22e2f000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f6e22c27000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00007f6e22a17000)
```

Running it under gdb goes like this:
```
Info: Agent running with pid '876719'.
Session: Starting session at 'Wed Jan 24 16:39:43 2018'.
Info: Using alpha channel in render extension.
nxagent: xcb_io.c:520: _XAllocID: Assertion `ret != inval_id' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff4e7e1f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install freetype-2.4.11-15.el7.x86_64 glibc-2.17-196.el7_4.2.x86_64 libX11-1.6.5-1.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXcomposite-0.4.4-4.1.el7.x86_64 libXcursor-1.1.14-8.el7.x86_64 libXdamage-1.1.4-4.1.el7.x86_64 libXdmcp-1.1.2-6.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXfixes-5.0.3-1.el7.x86_64 libXfont-1.5.2-1.el7.x86_64 libXi-1.7.9-1.el7.x86_64 libXinerama-1.1.3-2.1.el7.x86_64 libXpm-3.5.12-1.el7.x86_64 libXrandr-1.5.1-2.el7.x86_64 libXrender-0.9.10-1.el7.x86_64 libXtst-1.2.3-1.el7.x86_64 libfontenc-1.1.3-3.el7.x86_64 libgcc-4.8.5-16.el7_4.1.x86_64 libjpeg-turbo-1.2.90-5.el7.x86_64 libpng-1.5.13-7.el7_2.x86_64 libstdc++-4.8.5-16.el7_4.1.x86_64 libxcb-1.12-1.el7.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 pixman-0.34.0-1.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007ffff4e7e1f7 in raise () from /lib64/libc.so.6
#1  0x00007ffff4e7f8e8 in abort () from /lib64/libc.so.6
#2  0x00007ffff4e77266 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff4e77312 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff7adfdb3 in _XAllocID () from /lib64/libX11.so.6
#5  0x00007ffff7addf84 in XCreateWindow () from /lib64/libX11.so.6
#6  0x00000000004a6585 in nxagentOpenScreen (pScreen=<optimized out>, argc=<optimized out>, argv=<optimized out>) at Screen.c:1751
#7  0x000000000042f09e in AddScreen (pfnInit=0x4a5570 <nxagentOpenScreen>, argc=argc@entry=2, argv=argv@entry=0x7fffffffde48) at ../../dix/dispatch.c:4171
#8  0x00000000004a168f in InitOutput (screenInfo=0xb48ea0 <screenInfo>, argc=argc@entry=2, argv=argv@entry=0x7fffffffde48) at Init.c:394
#9  0x000000000040e60f in main (argc=2, argv=0x7fffffffde48, envp=<optimized out>) at main.c:278
```

Any ideas why it happens now (it has worked well with older snapshots)?

**Comment by Ionic** [comment]
It shouldn't link libX11 at all visibly. Can you please try the X2Go packages (not built yourself, but properly installed into the system)?

**Comment by realsimix** [comment]
OK, I've tested with the X2Go packages and it's basically the same there.

I also see how it is solved in the x2Go packages and doing it with my local build makes it work also:

ln -s libNX_X11.so.6.3.0 libX11.so.6

Thanks,
Simon

**Comment by Ionic** [comment]
"Basically the same", i.e., still crashing?

Yeah, you will need compatibility symlinks in the RPATH location built into nxagent. `readelf -d nxagent` will tell you where that is.

**Comment by realsimix** [comment]
Sorry for the confusion: it works if installed in the way the X2Go packages do it and it also works with my builds with the compatibility symlinks installed, as you said.

I've just missed it because older builds have worked without the compatibility symlinks for whatever reason.

**Comment by Ionic** [comment]
Probably for several reasons... in the past, we've been using `LD_LIBRARY_PATH` to point to the compat symlink location, but dropped this in favor of using `RPATH/RUNPATH`.

Good that it works!
